package persistencia;
// Generated Nov 16, 2015 3:40:15 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Evento generated by hbm2java
 */
@Entity
@Table(name = "evento", catalog = "cocasi")
public class Evento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idEvento;
	private Falla falla;
	private Date fechaIni;
	private Date fechaFin;
	private BigDecimal costoTotal;
	private String mitigante;

	public Evento() {
	}

	public Evento(Falla falla, Date fechaIni, Date fechaFin, BigDecimal costoTotal, String mitigante) {
		this.falla = falla;
		this.fechaIni = fechaIni;
		this.fechaFin = fechaFin;
		this.costoTotal = costoTotal;
		this.mitigante = mitigante;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_evento", unique = true, nullable = false)
	public Integer getIdEvento() {
		return this.idEvento;
	}

	public void setIdEvento(Integer idEvento) {
		this.idEvento = idEvento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_falla", nullable = false)
	public Falla getFalla() {
		return this.falla;
	}

	public void setFalla(Falla falla) {
		this.falla = falla;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_ini", nullable = false, length = 19)
	public Date getFechaIni() {
		return this.fechaIni;
	}

	public void setFechaIni(Date fechaIni) {
		this.fechaIni = fechaIni;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_fin", nullable = false, length = 19)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "costo_total", nullable = false, precision = 15)
	public BigDecimal getCostoTotal() {
		return this.costoTotal;
	}

	public void setCostoTotal(BigDecimal costoTotal) {
		this.costoTotal = costoTotal;
	}

	@Column(name = "mitigante", nullable = false, length = 150)
	public String getMitigante() {
		return this.mitigante;
	}

	public void setMitigante(String mitigante) {
		this.mitigante = mitigante;
	}

}
